### ISSUE TITLE
Default key version has not changed, still secret1

### ISSUE THREAD

**Issue by dev-guy** [jtgasper3/docker-shibboleth-idp#15]
I ran idp-reset.sh during my initial setup.

I'm getting the following message idp-process.log. I Googled for it, and it seems to happen to other Shibboleth idP users. I haven't found any information regarding which keystore this pertains to, or how to make it go away. 

I thought I would mention this here and I will post a question to the shib-users mail group.

[net.shibboleth.utilities.java.support.security.BasicKeystoreKeyStrategy:327]
- Default key version has not changed, still secret1

**Comment by jtgasper3** [comment]
I'm sorry I don't have any insight into this (https://issues.shibboleth.net/jira/browse/IDP-567). Looks like it might just be noise.

I just posted a beta https://github.com/jtgasper3/docker-shibboleth-idp/tree/3.1.2-beta. You might try that and see if it does the same thing.

But I'm going to close this as a not fix, since it is related to Shib and not the Docker image.

**Comment by terrisgit** [comment]
Yes, per https://issues.shibboleth.net/jira/browse/IDP-567 , this is just noise and the message might get changed to something less alarming
